"""FastAPI application for DocAssist."""
import asyncio
import json
import os
import uuid
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import BackgroundTasks, Depends, FastAPI, HTTPException, Request, Response, Security
from fastapi.responses import JSONResponse
from fastapi.security import APIKeyHeader
from fastapi.staticfiles import StaticFiles
from langgraph.checkpoint.sqlite.aio import AsyncSqliteSaver
from langgraph.types import Command
from pydantic import BaseModel
from typing import Literal
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from slowapi.util import get_remote_address

from agent.graph import build_graph, initial_state, render_pdf
from agent.models import BusinessProfile, ComplianceResult, InvoiceModel
from agent.jobs import create_job, get_job, init_jobs_db, update_job
from agent.observability import init_db as init_node_runs_db, persist_run

_api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)


def _require_api_key(api_key: str | None = Security(_api_key_header)) -> str:
    expected = os.environ.get("DOCASSIST_API_KEY", "")
    if not expected or api_key != expected:
        raise HTTPException(status_code=401, detail="Unauthorized")
    return api_key


_CLARIFICATION_TYPES = {"scope_clarification", "rate_clarification", "compliance_clarification"}


def _extract_clarification(snapshot) -> dict | None:
    """Return the interrupt value if the graph is paused at any clarification node."""
    try:
        for task in snapshot.tasks:
            for interrupt_item in getattr(task, "interrupts", ()):
                val = getattr(interrupt_item, "value", None)
                if isinstance(val, dict) and val.get("type") in _CLARIFICATION_TYPES:
                    return val
    except Exception:
        pass
    return None


async def _handle_graph_result(
    graph,
    result: dict,
    request_id: str,
    config: dict,
    db_path: Path,
) -> None:
    """Inspect the state returned by ainvoke and write the appropriate job status."""
    if result.get("error"):
        metadata = result.get("per_node_metadata") or []
        await asyncio.to_thread(persist_run, request_id, metadata, error=result["error"], db_path=db_path)
        await asyncio.to_thread(update_job, request_id, status="failed", error=result["error"], db_path=db_path)

    elif result.get("pdf_bytes") is not None:
        # Graph ran to completion — store pdf_bytes so GET /pdf/{id} can serve them.
        await asyncio.to_thread(
            update_job, request_id, status="completed", pdf_bytes=result["pdf_bytes"], db_path=db_path
        )

    else:
        # No pdf — the graph suspended at an interrupt or routed to END early.
        # Read the checkpoint to find out which case we're in.
        snapshot = None
        clarification = None
        try:
            snapshot = await graph.aget_state(config)
            clarification = _extract_clarification(snapshot)
        except Exception:
            pass

        if clarification:
            # Paused at scope_clarify, rate_clarify, or compliance_clarify.
            await asyncio.to_thread(
                update_job,
                request_id,
                status="awaiting_clarification",
                clarification_json=json.dumps(clarification),
                db_path=db_path,
            )
        elif result.get("quote") is not None and snapshot is not None and snapshot.tasks:
            # Has pending tasks but no clarification interrupt — must be human_review.
            await asyncio.to_thread(
                update_job,
                request_id,
                status="awaiting_approval",
                quote_json=json.dumps(result["quote"]),
                db_path=db_path,
            )
        elif result.get("quote") is not None:
            # Graph routed to END after exhausting compliance retries on non-clarifiable fields.
            await asyncio.to_thread(
                update_job,
                request_id,
                status="failed",
                error="Invoice generation failed: compliance requirements could not be met with the provided data.",
                db_path=db_path,
            )
        else:
            await asyncio.to_thread(
                update_job,
                request_id,
                status="failed",
                error="Graph suspended at unexpected point",
                db_path=db_path,
            )


async def _run_graph(
    graph,
    request_id: str,
    raw_input: str,
    db_path: Path,
    language_override: str | None = None,
    rate_overrides: dict | None = None,
) -> None:
    """Background task: run graph until an interrupt, then update jobs table."""
    state = initial_state(raw_input, language_override=language_override)
    state["request_id"] = request_id  # override UUID generated by initial_state()
    if rate_overrides:
        state["rate_overrides"] = rate_overrides
    config = {"configurable": {"thread_id": request_id}}

    try:
        result = await graph.ainvoke(state, config=config)
    except Exception as exc:
        await asyncio.to_thread(persist_run, request_id, [], error=str(exc), db_path=db_path)
        await asyncio.to_thread(update_job, request_id, status="failed", error=str(exc), db_path=db_path)
        return

    await _handle_graph_result(graph, result, request_id, config, db_path)


async def _resume_graph(
    graph,
    request_id: str,
    resume_value: dict,
    db_path: Path,
) -> None:
    """Background task: resume a graph that is paused at any interrupt."""
    config = {"configurable": {"thread_id": request_id}}

    try:
        result = await graph.ainvoke(Command(resume=resume_value), config=config)
    except Exception as exc:
        await asyncio.to_thread(persist_run, request_id, [], error=str(exc), db_path=db_path)
        await asyncio.to_thread(update_job, request_id, status="failed", error=str(exc), db_path=db_path)
        return

    await _handle_graph_result(graph, result, request_id, config, db_path)


def make_lifespan(db_path: Path):
    @asynccontextmanager
    async def lifespan(app: FastAPI):
        # NOTE: SQLite is ephemeral on Cloud Run — data is lost on container restart.
        # Use --min-instances=1 for demo, or mount a persistent volume for production.
        db_path.parent.mkdir(parents=True, exist_ok=True)
        await asyncio.to_thread(init_node_runs_db, db_path)
        await asyncio.to_thread(init_jobs_db, db_path)
        async with AsyncSqliteSaver.from_conn_string(str(db_path)) as checkpointer:
            app.state.graph = build_graph(checkpointer=checkpointer)
            app.state.db_path = db_path
            yield

    return lifespan


class QuoteRequest(BaseModel):
    raw_input: str
    language: Literal["de", "en"] | None = None
    rate_overrides: dict | None = None  # {"labor_hourly": 90.0, "labor_daily": 650.0}


class InvoiceRequest(BaseModel):
    profile_override: dict | None = None


class ClarifyRequest(BaseModel):
    clarified_input: str | None = None   # scope_clarification
    rates: dict | None = None            # rate_clarification: {service_description: rate_eur}
    compliance_data: dict | None = None  # compliance_clarification: {field_name: value}


class QuoteResponse(BaseModel):
    request_id: str


def create_app(db_path: Path | None = None) -> FastAPI:
    _db_path = db_path or Path(os.getenv("DB_PATH", "data/docassist.db"))
    limiter = Limiter(key_func=get_remote_address)
    app = FastAPI(title="DocAssist", version="0.10.0", lifespan=make_lifespan(_db_path))
    app.state.limiter = limiter
    app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

    @app.get("/health")
    def health():
        return {"status": "ok"}

    @app.get("/config")
    def get_config():
        return {"api_key": os.environ.get("DOCASSIST_API_KEY", "")}

    @app.get("/clients")
    def get_clients():
        import json
        from pathlib import Path as _Path
        clients_path = _Path(__file__).parent.parent / "data" / "clients.json"
        clients = json.loads(clients_path.read_text(encoding="utf-8"))
        return [{"name": c["name"], "short_names": c.get("short_names", [])} for c in clients]

    @app.get("/profile")
    def get_profile():
        import yaml
        from pathlib import Path as _Path
        profile_path = _Path(__file__).parent.parent / "config" / "business_profile.yaml"
        data = yaml.safe_load(profile_path.read_text(encoding="utf-8"))
        result = {k: v for k, v in data.items() if k != "default_rates"}
        rates = data.get("default_rates", {})
        result["labor_hourly"] = rates.get("labor_hourly")
        result["labor_daily"] = rates.get("labor_daily")
        return result

    @app.post("/quote", response_model=QuoteResponse, dependencies=[Depends(_require_api_key)])
    @limiter.limit(os.getenv("DOCASSIST_RATE_LIMIT", "5/day"))
    async def post_quote(
        request: Request,
        body: QuoteRequest,
        background_tasks: BackgroundTasks,
    ) -> QuoteResponse:
        request_id = str(uuid.uuid4())
        db = request.app.state.db_path
        graph = request.app.state.graph
        await asyncio.to_thread(create_job, request_id, db)
        background_tasks.add_task(_run_graph, graph, request_id, body.raw_input, db, body.language, body.rate_overrides)
        return QuoteResponse(request_id=request_id)

    @app.get("/status/{request_id}", dependencies=[Depends(_require_api_key)])
    async def get_status(request_id: str, request: Request) -> dict:
        db = request.app.state.db_path
        job = await asyncio.to_thread(get_job, request_id, db)
        if job is None:
            raise HTTPException(status_code=404, detail="Job not found")
        quote = json.loads(job["quote_json"]) if job.get("quote_json") else None
        clarification = json.loads(job["clarification_json"]) if job.get("clarification_json") else None
        return {
            "status": job["status"],
            "quote": quote,
            "clarification": clarification,
            "error": job.get("error"),
        }

    @app.post("/clarify/{request_id}", dependencies=[Depends(_require_api_key)])
    async def post_clarify(
        request_id: str,
        request: Request,
        body: ClarifyRequest,
        background_tasks: BackgroundTasks,
    ) -> dict:
        db = request.app.state.db_path
        graph = request.app.state.graph

        job = await asyncio.to_thread(get_job, request_id, db)
        if job is None:
            raise HTTPException(status_code=404, detail="Job not found")
        if job["status"] != "awaiting_clarification":
            raise HTTPException(
                status_code=409,
                detail=f"Job is not awaiting clarification (status: {job['status']})",
            )

        resume_value: dict = {
            "clarified_input": body.clarified_input or "",
            "rates": body.rates or {},
            **(body.compliance_data or {}),
        }
        await asyncio.to_thread(update_job, request_id, status="running", db_path=db)
        background_tasks.add_task(_resume_graph, graph, request_id, resume_value, db)
        return {"request_id": request_id}

    @app.post("/invoice/{request_id}", dependencies=[Depends(_require_api_key)])
    async def post_invoice(
        request_id: str,
        request: Request,
        background_tasks: BackgroundTasks,
        body: InvoiceRequest = InvoiceRequest(),
    ) -> JSONResponse:
        db = request.app.state.db_path
        graph = request.app.state.graph

        job = await asyncio.to_thread(get_job, request_id, db)
        if job is None:
            raise HTTPException(status_code=404, detail="Job not found")
        if job["status"] != "awaiting_approval":
            raise HTTPException(
                status_code=409,
                detail=f"Job is not awaiting approval (status: {job['status']})",
            )

        resume_value: dict = {"status": "approved", "feedback": None}
        await asyncio.to_thread(update_job, request_id, status="running", db_path=db)
        background_tasks.add_task(_resume_graph, graph, request_id, resume_value, db)
        return JSONResponse({"request_id": request_id}, status_code=202)

    @app.get("/pdf/{request_id}", dependencies=[Depends(_require_api_key)])
    async def get_pdf(request_id: str, request: Request) -> Response:
        db = request.app.state.db_path
        job = await asyncio.to_thread(get_job, request_id, db)
        if job is None:
            raise HTTPException(status_code=404, detail="Job not found")
        if job["status"] != "completed":
            raise HTTPException(status_code=409, detail=f"Job not completed (status: {job['status']})")
        pdf_bytes: bytes = job.get("pdf_bytes") or b""
        if not pdf_bytes:
            raise HTTPException(status_code=404, detail="PDF not available")
        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={"Content-Disposition": f'attachment; filename="invoice-{request_id}.pdf"'},
        )

    # Must be registered LAST — catches any path not matched by API routes above.
    _static_dir = Path(__file__).parent.parent / "static"
    if _static_dir.is_dir():
        app.mount("/", StaticFiles(directory=str(_static_dir), html=True), name="static")

    return app
