"""FastAPI application for DocAssist."""
import asyncio
import json
import os
import uuid
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import BackgroundTasks, Depends, FastAPI, HTTPException, Request, Response, Security
from fastapi.responses import JSONResponse
from fastapi.security import APIKeyHeader
from fastapi.staticfiles import StaticFiles
from langgraph.checkpoint.sqlite.aio import AsyncSqliteSaver
from langgraph.types import Command
from pydantic import BaseModel
from typing import Literal
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from slowapi.util import get_remote_address

from agent.graph import build_graph, initial_state, render_pdf
from agent.models import BusinessProfile, InvoiceModel
from agent.jobs import create_job, get_job, init_jobs_db, update_job
from agent.observability import init_db as init_node_runs_db, persist_run

_api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)


def _require_api_key(api_key: str | None = Security(_api_key_header)) -> str:
    expected = os.environ.get("DOCASSIST_API_KEY", "")
    if not expected or api_key != expected:
        raise HTTPException(status_code=401, detail="Unauthorized")
    return api_key


async def _run_graph(
    graph,
    request_id: str,
    raw_input: str,
    db_path: Path,
    language_override: str | None = None,
) -> None:
    """Background task: run graph until human-review interrupt, update jobs table."""
    state = initial_state(raw_input, language_override=language_override)
    state["request_id"] = request_id  # override UUID generated by initial_state()
    config = {"configurable": {"thread_id": request_id}}

    try:
        result = await graph.ainvoke(state, config=config)
    except Exception as exc:
        await asyncio.to_thread(persist_run, request_id, [], error=str(exc), db_path=db_path)
        await asyncio.to_thread(update_job, request_id, status="failed", error=str(exc), db_path=db_path)
        return

    if result.get("error"):
        metadata = result.get("per_node_metadata") or []
        await asyncio.to_thread(persist_run, request_id, metadata, error=result["error"], db_path=db_path)
        await asyncio.to_thread(update_job, request_id, status="failed", error=result["error"], db_path=db_path)
    elif result.get("quote") is not None and result.get("pdf_bytes") is None:
        # Suspended at node_human_review
        await asyncio.to_thread(
            update_job,
            request_id,
            status="awaiting_approval",
            quote_json=json.dumps(result["quote"]),
            db_path=db_path,
        )
    elif result.get("pdf_bytes") is not None:
        # Graph ran to completion without interrupt (node_persist already called persist_run)
        await asyncio.to_thread(update_job, request_id, status="completed", db_path=db_path)
    else:
        # Unexpected: scope/rate clarification interrupt or unknown state
        await asyncio.to_thread(
            update_job,
            request_id,
            status="failed",
            error="Graph suspended at unexpected point (scope or rate clarification needed)",
            db_path=db_path,
        )


def make_lifespan(db_path: Path):
    @asynccontextmanager
    async def lifespan(app: FastAPI):
        # NOTE: SQLite is ephemeral on Cloud Run — data is lost on container restart.
        # Use --min-instances=1 for demo, or mount a persistent volume for production.
        db_path.parent.mkdir(parents=True, exist_ok=True)
        await asyncio.to_thread(init_node_runs_db, db_path)
        await asyncio.to_thread(init_jobs_db, db_path)
        async with AsyncSqliteSaver.from_conn_string(str(db_path)) as checkpointer:
            app.state.graph = build_graph(checkpointer=checkpointer)
            app.state.db_path = db_path
            yield

    return lifespan


class QuoteRequest(BaseModel):
    raw_input: str
    language: Literal["de", "en"] | None = None


class InvoiceRequest(BaseModel):
    profile_override: dict | None = None


class QuoteResponse(BaseModel):
    request_id: str


def create_app(db_path: Path | None = None) -> FastAPI:
    _db_path = db_path or Path(os.getenv("DB_PATH", "data/docassist.db"))
    limiter = Limiter(key_func=get_remote_address)
    app = FastAPI(title="DocAssist", version="0.10.0", lifespan=make_lifespan(_db_path))
    app.state.limiter = limiter
    app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

    @app.get("/health")
    def health():
        return {"status": "ok"}

    @app.get("/config")
    def get_config():
        return {"api_key": os.environ.get("DOCASSIST_API_KEY", "")}

    @app.get("/clients")
    def get_clients():
        import json
        from pathlib import Path as _Path
        clients_path = _Path(__file__).parent.parent / "data" / "clients.json"
        clients = json.loads(clients_path.read_text(encoding="utf-8"))
        return [{"name": c["name"], "short_names": c.get("short_names", [])} for c in clients]

    @app.get("/profile")
    def get_profile():
        import yaml
        from pathlib import Path as _Path
        profile_path = _Path(__file__).parent.parent / "config" / "business_profile.yaml"
        data = yaml.safe_load(profile_path.read_text(encoding="utf-8"))
        return {k: v for k, v in data.items() if k != "default_rates"}

    @app.post("/quote", response_model=QuoteResponse, dependencies=[Depends(_require_api_key)])
    @limiter.limit("5/day")
    async def post_quote(
        request: Request,
        body: QuoteRequest,
        background_tasks: BackgroundTasks,
    ) -> QuoteResponse:
        request_id = str(uuid.uuid4())
        db = request.app.state.db_path
        graph = request.app.state.graph
        await asyncio.to_thread(create_job, request_id, db)
        background_tasks.add_task(_run_graph, graph, request_id, body.raw_input, db, body.language)
        return QuoteResponse(request_id=request_id)

    @app.get("/status/{request_id}", dependencies=[Depends(_require_api_key)])
    async def get_status(request_id: str, request: Request) -> dict:
        db = request.app.state.db_path
        job = await asyncio.to_thread(get_job, request_id, db)
        if job is None:
            raise HTTPException(status_code=404, detail="Job not found")
        quote = json.loads(job["quote_json"]) if job.get("quote_json") else None
        return {
            "status": job["status"],
            "quote": quote,
            "error": job.get("error"),
        }

    @app.post("/invoice/{request_id}", dependencies=[Depends(_require_api_key)])
    async def post_invoice(request_id: str, request: Request, body: InvoiceRequest = InvoiceRequest()) -> Response:
        db = request.app.state.db_path
        graph = request.app.state.graph

        job = await asyncio.to_thread(get_job, request_id, db)
        if job is None:
            raise HTTPException(status_code=404, detail="Job not found")
        if job["status"] != "awaiting_approval":
            raise HTTPException(
                status_code=409,
                detail=f"Job is not awaiting approval (status: {job['status']})",
            )

        config = {"configurable": {"thread_id": request_id}}
        try:
            result = await graph.ainvoke(
                Command(resume={"status": "approved", "feedback": None}),
                config=config,
            )
        except Exception as exc:
            await asyncio.to_thread(persist_run, request_id, [], error=str(exc), db_path=db)
            await asyncio.to_thread(update_job, request_id, status="failed", error=str(exc), db_path=db)
            raise HTTPException(status_code=500, detail="Graph resume failed") from exc

        pdf_bytes: bytes = result.get("pdf_bytes") or b""

        if body.profile_override and result.get("invoice"):
            try:
                import yaml
                from pathlib import Path as _Path
                base = yaml.safe_load(
                    (_Path(__file__).parent.parent / "config" / "business_profile.yaml")
                    .read_text(encoding="utf-8")
                )
                base.update({k: v for k, v in body.profile_override.items() if v is not None})
                profile = BusinessProfile(**base)
                invoice = InvoiceModel.model_validate(result["invoice"])
                pdf_bytes = await asyncio.to_thread(render_pdf, invoice, profile)
            except Exception:
                pass  # fall back to graph-rendered pdf_bytes

        await asyncio.to_thread(update_job, request_id, status="completed", pdf_bytes=pdf_bytes, db_path=db)
        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={"Content-Disposition": f'attachment; filename="invoice-{request_id}.pdf"'},
        )

    # Must be registered LAST — catches any path not matched by API routes above.
    _static_dir = Path(__file__).parent.parent / "static"
    if _static_dir.is_dir():
        app.mount("/", StaticFiles(directory=str(_static_dir), html=True), name="static")

    return app
